# Generated by Django 2.1.7 on 2022-04-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211123_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetestresult',
            name='request_body',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='请求data'),
        ),
        migrations.AddField(
            model_name='casetestresult',
            name='request_header',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='请求header'),
        ),
        migrations.AddField(
            model_name='casetestresult',
            name='take_up_time',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='运行时间'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cron',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='cron表达式'),
        ),
        migrations.AddField(
            model_name='plan',
            name='project_id',
            field=models.IntegerField(default=None, null=True, verbose_name='项目id'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='creator',
            field=models.CharField(max_length=50, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='end_time',
            field=models.CharField(max_length=100, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='is_delete',
            field=models.CharField(choices=[(0, '否'), (1, '是')], default=0, max_length=20, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='project_id',
            field=models.IntegerField(null=True, verbose_name='项目id'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='run_people',
            field=models.CharField(default='sys', max_length=100, verbose_name='运行人'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='run_result',
            field=models.CharField(max_length=10, null=True, verbose_name='运行结果'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='run_time',
            field=models.CharField(max_length=100, null=True, verbose_name='运行耗时'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='start_time',
            field=models.CharField(max_length=100, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='update_person',
            field=models.CharField(max_length=50, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterModelTable(
            name='taskhistory',
            table='plan_run_history',
        ),
    ]
