# Generated by Django 2.1.7 on 2022-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monior', '0002_auto_20220423_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexploration_ruletable',
            name='tableschema',
            field=models.CharField(max_length=100, null=True, verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='dataexploration_questionhandlehistory',
            name='createDate',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_questioninfo',
            name='createDate',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_questioninfo',
            name='currentAssignmentTime',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='当前指派时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_tablehistory',
            name='createDate',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_tablehistory',
            name='modifyDate',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_tablehistory',
            name='probeTime',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='探查时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_testcase',
            name='LastProbeTime',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='最近探查时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_testcase',
            name='createDate',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_testcase',
            name='modifyDate',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_testcaserunhistory',
            name='endtime',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='dataexploration_testcaserunhistory',
            name='starttime',
            field=models.CharField(default='2022-04-24 17:26:45', max_length=100, verbose_name='开始时间'),
        ),
    ]
